language: java
dist: bionic

branches:
  only:
  - staging
  - production

env:
  global:
    - EXPO_SDK_VERSION="39.0.3"
    - TURTLE_VERSION="0.19.1"
    - NODE_VERSION="14.15.1"
    - YARN_VERSION="1.22.5"

jobs:
  include:
    - stage: publish app
      if: branch = staging
      env:
        - CACHE_NAME=publish YARN_CACHE_FOLDER="/home/travis/yarn_cache"
      cache:
        directories:
          - $HOME/yarn_cache
      before_install:
        - nvm install $NODE_VERSION
        - nvm use $NODE_VERSION
        - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version $YARN_VERSION
        - export PATH="$HOME/.yarn/bin:$PATH"
        - sudo apt-get update
        - sudo apt-get -y install libsecret-1-0
      install:
        - yarn global add expo-cli
      script:
        - openssl aes-256-cbc -k $DECRYPT_GOOGLE_SERVICES_ENC_KEY -in ./src/assets/firebase/google-services.json.enc -out ./src/assets/firebase/google-services.json -d
        - openssl aes-256-cbc -k $DECRYPT_GOOGLE_SERVICES_ENC_KEY -in ./src/assets/firebase/GoogleService-Info.plist.enc -out ./src/assets/firebase/GoogleService-Info.plist -d
        - expo login -u $EXPO_USERNAME -p $EXPO_PASSWORD --non-interactive
        - yarn
        - expo publish
    - stage: build standalone apps
      if: branch = production
      env:
        - CACHE_NAME=build-android-v3 YARN_CACHE_FOLDER="/home/travis/yarn_cache"
      jdk: openjdk8
      cache:
        directories:
          - $HOME/.turtle
          - $HOME/yarn_cache
          - $HOME/.gradle/wrapper
      before_install:
        - nvm install $NODE_VERSION
        - nvm use $NODE_VERSION
        - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version $YARN_VERSION
        - export PATH="$HOME/.yarn/bin:$PATH"
        - sudo apt-get update
        - sudo apt-get -y install libsecret-1-0
      install:
        - pip install --user awscli
        - yarn global add gulp-cli turtle-cli@$TURTLE_VERSION
      script:
        - yarn
        - openssl aes-256-cbc -k $DECRYPT_GOOGLE_SERVICES_ENC_KEY -in ./src/assets/firebase/google-services.json.enc -out ./src/assets/firebase/google-services.json -d
        - export ARTIFACT_PATH="/home/travis/expo-project-$TRAVIS_COMMIT-`date +%s`.aab"
        - turtle setup:android --sdk-version $EXPO_SDK_VERSION > /dev/null || travis_terminate 1
        - echo $EXPO_ANDROID_KEYSTORE_BASE64 > expo-project.jks.base64
        - base64 --decode expo-project.jks.base64 > expo-project.jks
        - turtle build:android
            --keystore-path ./expo-project.jks
            --keystore-alias $EXPO_ANDROID_KEYSTORE_ALIAS
            --type app-bundle
            -o $ARTIFACT_PATH
      after_success:
        - aws s3 cp $ARTIFACT_PATH s3://$AWS_BUCKET/`basename $ARTIFACT_PATH`
    - stage: build standalone apps
      if: branch = production
      os: osx
      osx_image: xcode11.2
      language: node_js
      node_js: $NODE_VERSION
      env:
        - CACHE_NAME=build-ios-ipa YARN_CACHE_FOLDER="/Users/travis/yarn_cache"
      cache:
        directories:
          - $HOME/.turtle
          - $HOME/yarn_cache
      before_install:
        - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version $YARN_VERSION
        - export PATH="$HOME/.yarn/bin:$PATH"
      install:
        - python3 -m pip install --user awscli
        - python3 -V
        - export PATH=/Users/travis/Library/Python/3.7/bin:$PATH
        - yarn global add turtle-cli@$TURTLE_VERSION
      script:
        - yarn
        - openssl aes-256-cbc -k $DECRYPT_GOOGLE_SERVICES_ENC_KEY -in ./src/assets/firebase/GoogleService-Info.plist.enc -out ./src/assets/firebase/GoogleService-Info.plist -md sha256 -d
        - export ARTIFACT_PATH="/Users/travis/expo-project-$TRAVIS_COMMIT-`date +%s`.ipa"
        - turtle setup:ios --sdk-version $EXPO_SDK_VERSION || travis_terminate 1
        - echo $EXPO_IOS_DIST_P12_BASE64 > expo-project_dist.p12.base64
        - base64 --decode expo-project_dist.p12.base64 > expo-project_dist.p12
        - echo $EXPO_IOS_PROVISIONING_PROFILE_BASE64 > expo-project.mobileprovision.base64
        - base64 --decode expo-project.mobileprovision.base64 > expo-project.mobileprovision
        - turtle build:ios
            --team-id $EXPO_APPLE_TEAM_ID
            --dist-p12-path ./expo-project_dist.p12
            --provisioning-profile-path ./expo-project.mobileprovision
            -o $ARTIFACT_PATH
      after_success:
        - aws s3 cp $ARTIFACT_PATH s3://$AWS_BUCKET/`basename $ARTIFACT_PATH`