version: 2.1
publish: &publish
  working_directory: ~/publish-to-expo
  docker:
    - image: circleci/node:14.15.1
  steps:
    - checkout

    - run:
        name: helpcmd
        command: openssl aes-256-cbc -ciphers

    - run:
        name: helpcmd2
        command: openssl version

    - run:
        name: decrypt google-services.json
        command: openssl aes-256-cbc -aes-256-cbc -k $DECRYPT_GOOGLE_SERVICES_ENC_KEY -in ./src/assets/firebase/google-services.json.enc -out ./src/assets/firebase/google-services.json -d

    - run:
        name: decrypt GoogleService-Info.plist
        command: openssl aes-256-cbc -aes-256-cbc -k $DECRYPT_GOOGLE_SERVICES_ENC_KEY -in ./src/assets/firebase/GoogleService-Info.plist.enc -out ./src/assets/firebase/GoogleService-Info.plist -d

    - run:
        name: Installing dependencies
        command: yarn

    - run:
        name: Add global expo-cli
        command: yarn global add expo-cli

    - run:
        name: Login into Expo
        command: npx expo-cli login -u $EXPO_USERNAME -p $EXPO_PASSWORD

    - run:
        name: Publish to Expo
        command: npx expo-cli publish --non-interactive

test: &test
  working_directory: ~/my-app
  docker:
    - image: circleci/node:14.15.1
  steps:
    - checkout

    - run:
        name: test
        command: yarn test

jobs:
  publish_to_expo:
    <<: *publish
  test_app:
    <<: *test
  fastlane_release:
    working_directory: ~/deploy-app
    docker:
      - image: circleci/node:14.15.1
        environment:
            EXPO_SDK_VERSION: 40.0.1
            TURTLE_VERSION: 0.20.7
            NODE_VERSION: 14.15.1
            YARN_VERSION: 1.22.5
    steps:
      - checkout
      - run:
          name: Install packages
          command: |
              yarn global add gulp-cli turtle-cli@$TURTLE_VERSION
              gpg --keyserver hkp://pool.sks-keyservers.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
              curl -sSL https://get.rvm.io | bash -s stable --ruby
              rvm install 2.4
              sudo gem install fastlane
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: Prepare keys
          command: |
              export ARTIFACT_PATH="/home/travis/expo-project-$CIRCLE_SHA1-`date +%s`.aab"
              echo $EXPO_ANDROID_KEYSTORE_BASE64 > expo-project.jks.base64
              base64 --decode expo-project.jks.base64 > expo-project.jks
              echo $GOOGLE_API_ACCESS_UPLOAD > google-api-access.json.base64
              base64 --decode google-api-access.json.base64 > google-api-access.json
      - run:
          name: Build and Supply
          command: |
              turtle setup:android --sdk-version $EXPO_SDK_VERSION > /dev/null
              turtle build:android --keystore-path ./expo-project.jks --keystore-alias $EXPO_ANDROID_KEYSTORE_ALIAS --type app-bundle -o $ARTIFACT_PATH
              fastlane supply --track 'internal' --aab $ARTIFACT_PATH --json_key google-api-access.json --skip_upload_images --skip_upload_screenshots

workflows:
  version: 2
  deploy:
    jobs:
      - fastlane_release
  