version: 2.1

jobs:
  publish_to_expo:
    working_directory: ~/publish-to-expo
    resource_class: medium+
    docker:
      - image: circleci/node:14.15.1
    environment:
      EXPO_API_BASE_URL: $EXPO_API_BASE_URL_STAGING
      EXPO_JSON_RPC_URL: $EXPO_JSON_RPC_URL_STAGING
      EXPO_BLOCK_EXPLORER_URL: $EXPO_BLOCK_EXPLORER_URL_STAGING
      EXPO_CUSD_CONTRACT_ADDRESS: $EXPO_CUSD_CONTRACT_ADDRESS_STAGING
      EXPO_IS_TESTNET: true
      SENTRY_ORG: impactmarket
      SENTRY_PROJECT: impactmarket
      SENTRY_ENVIRONMENT: dev
      SENTRY_DEPLOY_ENV: dev
    steps:
      - checkout

      - run:
          name: decrypt google-services.json
          command: openssl aes-256-cbc -aes-256-cbc -k $DECRYPT_GOOGLE_SERVICES_ENC_KEY -in ./src/assets/firebase/google-services.json.enc -out ./src/assets/firebase/google-services.json -d

      - run:
          name: decrypt GoogleService-Info.plist
          command: openssl aes-256-cbc -aes-256-cbc -k $DECRYPT_GOOGLE_SERVICES_ENC_KEY -in ./src/assets/firebase/GoogleService-Info.plist.enc -out ./src/assets/firebase/GoogleService-Info.plist -d

      - run:
          name: Installing dependencies
          command: yarn

      - run:
          name: Add global expo-cli
          command: yarn global add expo-cli

      - run:
          name: Login into Expo
          command: npx expo-cli login -u $EXPO_USERNAME -p $EXPO_PASSWORD

      - run:
          name: Publish to Expo and Create release, notify Sentry of deploy
          command: |
            curl -sL https://sentry.io/get-cli/ | bash
            export SENTRY_RELEASE=$(sentry-cli releases propose-version)
            sentry-cli releases new -p $SENTRY_PROJECT $SENTRY_RELEASE
            sentry-cli releases set-commits $SENTRY_RELEASE --auto
            npx expo-cli publish --non-interactive
            sentry-cli releases finalize $SENTRY_RELEASE
            sentry-cli releases deploys $SENTRY_RELEASE new -e $SENTRY_ENVIRONMENT

      - run:
          name: Publish to Expo
          command: 'curl -X POST -H "Content-type: application/json" --data ''{"text":"New version deployed! Visit https://expo.io/@impactmarket/projects/impact-market"}'' $SLACK_WEBHOOK_DEPLOY_EXPO'

  unit_test:
    working_directory: ~/my-app
    docker:
      - image: circleci/node:14.15.1
    environment:
      NODE_ENV: development
    steps:
      - checkout

      - run:
          name: Installing dependencies
          command: yarn

      - run:
          name: test
          command: yarn test

  type_checks:
    working_directory: ~/my-app
    docker:
      - image: circleci/node:14.15.1
    environment:
      NODE_ENV: development
    steps:
      - checkout

      - run:
          name: Installing dependencies
          command: yarn

      - run:
          name: typescript verifications
          command: yarn tsc

workflows:
  version: 2
  expo:
    jobs:
      - publish_to_expo
  everyday:
    jobs:
      - unit_test
      - type_checks
