version: 2.1
publish: &publish
  working_directory: ~/publish-to-expo
  docker:
    - image: circleci/node:14.15.1
  steps:
    - checkout

    - run:
        name: decrypt google-services.json
        command: openssl aes-256-cbc -k $DECRYPT_GOOGLE_SERVICES_ENC_KEY -in ./src/assets/firebase/google-services.json.enc -out ./src/assets/firebase/google-services.json -d

    - run:
        name: decrypt GoogleService-Info.plist
        command: openssl aes-256-cbc -k $DECRYPT_GOOGLE_SERVICES_ENC_KEY -in ./src/assets/firebase/GoogleService-Info.plist.enc -out ./src/assets/firebase/GoogleService-Info.plist -d

    - run:
        name: Installing dependencies
        command: yarn

    - run:
        name: Add global expo-cli
        command: yarn global add expo-cli

    - run:
        name: Login into Expo
        command: yarn expo-cli login -u $EXPO_USERNAME -p $EXPO_PASSWORD

    - run:
        name: Publish to Expo
        command: yarn expo-cli publish --non-interactive

deploy: &deploy
  working_directory: ~/deploy-ios
  macos:
      xcode: "11.3"
  steps:
    - checkout

    - run:
        name: Install fastlane
        command: bundle install
    - run:
        name: Execute fastlane
        command: bundle exec fastlane playstore

test: &test
  working_directory: ~/my-app
  docker:
    - image: circleci/node:14.15.1
  steps:
    - checkout

    - run:
        name: test
        command: yarn test

jobs:
  publish_to_expo:
    <<: *publish
  deploy_to_store:
    <<: *deploy
  test_app:
    <<: *test

workflows:
  version: 2
  test:
    jobs:
      - test_app
  build:
    jobs:
      - publish_to_expo
  deploy:
    jobs:
      - deploy_to_store