version: 2.1
publish: &publish
  working_directory: ~/publish-to-expo
  docker:
    - image: circleci/node:14.15.1
  steps:
    - checkout

    - run:
        name: helpcmd
        command: openssl aes-256-cbc -ciphers

    - run:
        name: helpcmd2
        command: openssl version

    - run:
        name: decrypt google-services.json
        command: openssl aes-256-cbc -aes-256-cbc -k $DECRYPT_GOOGLE_SERVICES_ENC_KEY -in ./src/assets/firebase/google-services.json.enc -out ./src/assets/firebase/google-services.json -d

    - run:
        name: decrypt GoogleService-Info.plist
        command: openssl aes-256-cbc -aes-256-cbc -k $DECRYPT_GOOGLE_SERVICES_ENC_KEY -in ./src/assets/firebase/GoogleService-Info.plist.enc -out ./src/assets/firebase/GoogleService-Info.plist -d

    - run:
        name: Installing dependencies
        command: yarn

    - run:
        name: Add global expo-cli
        command: yarn global add expo-cli

    - run:
        name: Login into Expo
        command: npx expo-cli login -u $EXPO_USERNAME -p $EXPO_PASSWORD

    - run:
        name: Publish to Expo
        command: npx expo-cli publish --non-interactive

test: &test
  working_directory: ~/my-app
  docker:
    - image: circleci/node:14.15.1
  steps:
    - checkout

    - run:
        name: test
        command: yarn test

jobs:
  publish_to_expo:
    <<: *publish
  test_app:
    <<: *test
  fastlane_release:
    executor: rn/linux_js
    docker:
      - image: circleci/ruby:2.7.2
        environment:
            EXPO_SDK_VERSION: 40.0.1
            TURTLE_VERSION: 0.20.7
            NODE_VERSION: 14.15.1
            YARN_VERSION: 1.22.5
    steps:
      - run:
          name: "Update Node.js and npm"
          command: |
            curl -sSL "https://nodejs.org/dist/v14.15.1/node-v14.15.1-linux-x64.tar.xz" | sudo tar --strip-components=2 -xJ -C /usr/local/bin/ node-v14.15.1-linux-x64/bin/node
            curl https://www.npmjs.com/install.sh | sudo bash
            sudo npm install --global yarn
      - attach_workspace:
          at: .
      - rn/yarn_install
      - run:
          name: Install fastlane
          command: export ARTIFACT_PATH="/home/travis/expo-project-$CIRCLE_SHA1-`date +%s`.aab"
      - run:
          name: Install fastlane
          command: echo $EXPO_ANDROID_KEYSTORE_BASE64 > expo-project.jks.base64
      - run:
          name: Install fastlane
          command: base64 --decode expo-project.jks.base64 > expo-project.jks
      - run:
          name: Install fastlane
          command: yarn global add gulp-cli turtle-cli@$TURTLE_VERSION
      - run:
          name: Install fastlane
          command: turtle setup:android --sdk-version $EXPO_SDK_VERSION > /dev/null
      - run:
          name: Install fastlane
          command: npx turtle build:android
            --keystore-path ./expo-project.jks
            --keystore-alias $EXPO_ANDROID_KEYSTORE_ALIAS
            --type app-bundle
            -o $ARTIFACT_PATH
      - run:
          name: Install fastlane
          command: sudo gem install fastlane
      - run:
          name: Install fastlane
          command: echo $GOOGLE_API_ACCESS_UPLOAD > google-api-access.json.base64
      - run:
          name: Install fastlane
          command: base64 --decode google-api-access.json.base64 > google-api-access.json
      - run:
          command: fastlane supply --track 'internal' --aab $ARTIFACT_PATH --json_key google-api-access.json --skip_upload_images  --skip_upload_screenshots
          name: Run Fastlane

orbs:
  rn: react-native-community/react-native@1.0.0

workflows:
  version: 2
  deploy:
    jobs:
      - fastlane_release
  