/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

/// <reference types="truffle-typings" />

import * as TruffleContracts from ".";

declare global {
  namespace Truffle {
    interface Artifacts {
      require(name: "Community"): TruffleContracts.CommunityContract;
      require(name: "Context"): TruffleContracts.ContextContract;
      require(name: "cUSD"): TruffleContracts.cUSDContract;
      require(name: "ImpactMarket"): TruffleContracts.ImpactMarketContract;
      require(name: "Migrations"): TruffleContracts.MigrationsContract;
      require(
        name: "WhitelistAdminRole"
      ): TruffleContracts.WhitelistAdminRoleContract;
      require(
        name: "WhitelistedCommunity"
      ): TruffleContracts.WhitelistedCommunityContract;
      require(
        name: "WhitelistedUser"
      ): TruffleContracts.WhitelistedUserContract;
    }
  }
}
